notification:
    domain: https://temp-react-for-heroku.herokuapp.com
wash:
    required:
        scheduling: 1800000
logging:
    level:
        org:
            springframework:
                security: ERROR