fcm:
    api:
        key: AAAA4Qf9ZfU:APA91bHRg0dm5lSb7jNPFWnOrC2qU_T5uBfq2MfpphaFBREkrA1_AAJkx_kt3kJshZGcOcj-6ryQv1M2qj8BTwf0joYC9SO7wIZcHwA2-qCard_vZOD3DZXGvc8m3bHL7Mddptcb6TJ-
        url: https://fcm.googleapis.com/fcm/send
logging:
    level:
        org:
            springframework:
                security: INFO
notification:
    domain: http://localhost:3000
dirty:
    clothes:
        notification:
            scheduling: 120000
            enabled: true
security:
    oauth2:
        resource:
            id: resource-id1
            jwt:
                keyValue: |-
                    -----BEGIN PUBLIC KEY-----
                    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
                    -----END PUBLIC KEY-----
server:
    contextPath: /resource
    port: 9000
liquibase:
    enabled: false
spring:
    profiles:
        active: ${activeProfile}
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost/wash
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
        show-sql: false
