notification:
    domain: https://temp-react-for-heroku.herokuapp.com
dirty:
    clothes:
        notification:
            scheduling: 1800000
            enabled: true
logging:
    level:
        org:
            springframework:
                security: ERROR